services:
  itvdelab:
    image: dgadiraju/itvdelab
    hostname: itvdelab
    ports:
      - "8888:8888"
    volumes:
      - "./configs:/home/itversity/configs"
      - "./data:/data"
    environment:
      SHELL: /bin/bash
    networks:
      - itvdelabnw
    depends_on:
      - "cluster_util_db"
  cluster_util_db:
    image: postgres:13
    ports:
      - "6432:5432"
    volumes:
      - ./cluster_util_db_scripts:/docker-entrypoint-initdb.d
    networks:
      - itvdelabnw
    environment:
      POSTGRES_PASSWORD: itversity
networks:
  itvdelabnw:
    name: itvdelabnw
